name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build custom Docker image
        run: docker build -t myarchlinux:updated-packages -f Dockerfile-updated-packages .

      - name: Upgrade Packages in Container
        run: |
          docker run -it --rm myarchlinux:updated-packages /bin/bash -c "echo 'Packages are already updated'"
