# name: CI

 on:
   push:
     branches:
       - main
   pull_request:
     branches:
       - main

 jobs:
   build:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout repository
         uses: actions/checkout@v3

       - name: Part 1
         run: sudo apt install qemu   -y

       - name: Part 2
         run: sudo apt install docker -y


       - name: Part 3
         run: sudo docker build -t archiso-builder .
