name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download the Arch Linux image
        run: docker pull archlinux

      - name: Run the Arch Linux container
        run: docker run -it --rm archlinux /bin/bash
