name: ci

on:
  push:

jobs:
  qemu:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Download Arch Linux ISO
        run: |
          wget https://releases.ubuntu.com/22.04.3/ubuntu-22.04.3-desktop-amd64.iso
        # Replace '<version>' with the actual version you want to download

      - name: Start QEMU with Arch Linux ISO
        run: |
          qemu-system-x86_64 ubuntu-22.04.3-desktop-amd64.iso -m 2G -cdrom 
